import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/styles/globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/shared/components/query-provider";
import { Toaster } from "react-hot-toast";
import { MantineProvider } from "@mantine/core";
import Header from "./components/common/header/Header";
import Footer from "./components/common/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto max-w-[750px] antialiased`}
      >
        <QueryProvider>
          <MantineProvider>
            <Header />
            {children} <Footer />
          </MantineProvider>
        </QueryProvider>
        <Toaster position="bottom-center" reverseOrder={false} />
      </body>
    </html>
  );
}
